config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get  ':podcast_path/subscribe'          => 'podcasts#subscribe_new',     :as => :podcast_subscribe_new
  post ':podcast_path/subscribe'          => 'podcasts#subscribe_create',  :as => :podcast_subscribe_create
  get  ':podcast_path/subscribe_success'  => 'podcasts#subscribe_success', :as => :podcast_subscribe_success
  get  ':podcast_path/subscribe_error'    => 'podcasts#subscribe_error',   :as => :podcast_subscribe_error
  get  ':podcast_path/:episode_number'    => 'episodes#show',              :as => :episode
  get  ':podcast_path'                    => 'podcasts#show',              :as => :podcast

  root 'podcasts#index'

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :category_podcast_associations
  has_many :categories, through: :category_podcast_associations
  has_many :episodes
  mount_uploader :image, ImageUploader

  def episode(number)
    episodes.where(:number => number).first
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :subscribe_new, :subscribe_create, :subscribe_success, :subscribe_error]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.where(:public => true).order(:updated_at => :desc)
    @meta_title = Brick::SITETITLE
    @podcast_header_wrapper = 'all'
  end

  # GET /podcast_path
  # GET /podcast_path.json
  # GET /podcast_path.rss
  def show
    @episodes         = @podcast.episodes.published
    @meta_url         = view_context.podcast_url(@podcast)
    @meta_type        = "article"
    @meta_title       = @podcast.title
    @meta_image       = @podcast.image
    @meta_description = @podcast.body
    @podcast_header_wrapper = 'all'
  end

  def subscribe_new
    # if cookies["brickcaster_#{@podcast.path}_subscriber"].present?
    #   redirect_to podcast_subscribe_error_path(:podcast_path => @podcast.path, :message => "You are already subscribed!") and return
    # end
    if params[:email].present?
      begin
        subscribe_email(params[:email])
        redirect_to podcast_subscribe_success_path(:podcast_path => @podcast.path) and return
      rescue Gibbon::MailChimpError => e
        redirect_to podcast_subscribe_error_path(:podcast_path => @podcast.path, :message => e.message) and return
      end
    end
    @podcast_show_header = false
    @podcast_show_footer = false
  end

  def subscribe_create
    begin
      subscribe_email(params[:email][:address])
      redirect_to podcast_subscribe_success_path(:podcast_path => @podcast.path) and return
    rescue Gibbon::MailChimpError => e
      redirect_to podcast_subscribe_error_path(:podcast_path => @podcast.path, :message => e.message) and return
    end
  end

  def subscribe_success
    @podcast_show_header = false
    @podcast_show_footer = false
  end

  def subscribe_error
    @podcast_show_header = false
    @podcast_show_footer = false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find_by_path(params[:podcast_path]) if params[:podcast_path]
      redirect_to(root_path) and return unless @podcast.present?
    end

    def subscribe_email(email)
      @list_id = @podcast.email.present? ? @podcast.email : "61a457b26b"
      gb = Gibbon::Request.new
      gb.lists(@list_id).members.create(body: {:email_address => email, :status => "subscribed"})
      cookies.permanent["brickcaster_#{@podcast.path}_subscriber"] = true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def podcast_params
    #   params.require(:podcast).permit(:path, :title, :body, :image, :author, :keywords, :category_ids => [])
    # end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
  def podcast_path(podcast, options={})
    url_for(options.merge(:controller => 'podcasts', :action => 'show', :podcast_path => podcast.path, :only_path => true))
  end

  def podcast_url(podcast, options={})
    url_for(options.merge(:controller => 'podcasts', :action => 'show', :podcast_path => podcast.path, :only_path => false))
  end
end

app/views/podcasts/_header.html.erb
<div class="podcast-header <%= wrapper_class %>">
  <div class="inner">
    <div class="main">
      <div class="left">
        <%= cl_image_tag(podcast.image, :alt => podcast.title, :width => 220, :height => 220, :crop => :scale) %>
      </div>
      <div class="right">
        <h1 class="title"><%= link_to podcast.title, podcast_path(podcast) %></h1>
        <div class="body"><%= podcast.body %></div>
      </div>
    </div>
    <% if show_form %>
      <div class="cta highlight-link"><%= link_to "Subscribe by Email", podcast_subscribe_new_path(:podcast_path => podcast.path) %></div>
    <% end %>
  </div>
</div>

app/views/podcasts/_subscribe_new.html.erb
<h2 class="cta">Get new episodes delivered straight to your inbox.</h2>
<%= form_tag(podcast_subscribe_create_path(:podcast_path => podcast.path), method: "post", id: "subscribe") do -%>
   <%= email_field(:email, :address, {id: "email", placeholder: "email address"}) %>
   <%= submit_tag("Subscribe by Email!") %>
<% end %>

app/views/podcasts/index.html.erb
<% @podcasts.each do |podcast| %>
  <%= render :partial => "podcasts/header", :locals => {podcast: podcast, show_form: false, wrapper_class: @podcast_header_wrapper} %>
<% end %>

app/views/podcasts/show.html.erb
<ul class="episode-list">
  <% @episodes.each do |episode| %>
    <li class="episode-link"><%= link_to episode.title, episode_path(episode) %></li>
  <% end %>
</ul>

<% content_for :header do %>
  <h2><%= link_to Brick::SITENAME, root_path %> &gt; <%= link_to @podcast.title, podcast_path(@podcast) %></h2>
<% end %>

app/views/podcasts/subscribe_error.html.erb
<h1>Sorry...We've got a problem in the pipes!</h1>
<h2><%= params[:message] %></h2>
<p><%= link_to("Return to the podcast, already in session", podcast_path(@podcast)) %></p>

app/views/podcasts/subscribe_new.html.erb
<h1>Subscribe to the <%= @podcast.title %>!</h1>
<p>Get new episodes delivered straight to your inbox.</p>
<%= form_tag(podcast_subscribe_create_path(:podcast_path => @podcast.path), method: "post", id: "subscribe") do -%>
   <%= email_field(:email, :address, {id: "email", placeholder: "email address"}) %>
   <%= submit_tag("Sign me up!") %>
<% end %>

app/views/podcasts/subscribe_success.html.erb
<h1>Success! You are now subscribed to the <%= @podcast.title %>!</h1>
<p><%= link_to("Return to the podcast, already in session", podcast_path(@podcast)) %></p>