config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get  ':podcast_path/subscribe'          => 'podcasts#subscribe_new',     :as => :podcast_subscribe_new
  post ':podcast_path/subscribe'          => 'podcasts#subscribe_create',  :as => :podcast_subscribe_create
  get  ':podcast_path/subscribe_success'  => 'podcasts#subscribe_success', :as => :podcast_subscribe_success
  get  ':podcast_path/subscribe_error'    => 'podcasts#subscribe_error',   :as => :podcast_subscribe_error
  get  ':podcast_path/:episode_number'    => 'episodes#show',              :as => :episode
  get  ':podcast_path'                    => 'podcasts#show',              :as => :podcast

  root 'podcasts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @meta_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <link href="https://plus.google.com/107355867909504468216" rel="publisher">

  <meta property="og:title"       content="<%= @meta_title %>">
  <meta property="og:image"       content="<%= @meta_image %>">
  <meta property="og:site_name"   content="<%= @meta_sitename %>">
  <meta property="og:description" content="<%= @meta_description %>">
  <meta property="og:url"         content="<%= @meta_url %>">
  <meta property="fb:admins"      content="<%= @meta_fb_admins %>">
  <meta property="fb:app_id"      content="<%= @meta_fb_app_id %>">

  <meta name="twitter:card"        content="summary_large_image">
  <meta name="twitter:site"        content="<%= @meta_twitter_site %>">
  <meta name="twitter:creator"     content="<%= @meta_twitter_creator %>">
  <meta name="twitter:title"       content="<%= @meta_title %>">
  <meta name="twitter:description" content="<%= @meta_description %>">
  <meta name="twitter:image"       content="<%= @meta_image %>">
</head>
<body>

<div id="notice"><%= notice %></div>

<header class="navigation" role="banner">
  <div class="inner">
    <nav role="navigation" class="navigation">
      <% unless @podcast %>
        <a href="/" class="site-name">The <%= Brick::SITENAME %> podcast network</a>
      <% else %>
        <a href="<%= podcast_path(@podcast) %>" class="site-name podcast-name"><%= @podcast.title.upcase %></a>
      <% end %>
    </nav>

    <div class="social">
      <% if @podcast %>
        <%= link_to "RSS", podcast_url(@podcast, :format => :rss) %>
        <% if @podcast.itunes.present? %><%= link_to "iTunes", @podcast.itunes %><% end %>
        <%= link_to "Subscribe by Email", podcast_subscribe_new_path(podcast_path: @podcast.path), class: 'highlight' %>
      <% end %>
    </div>
  </div>
</header>

<section class="social-sharing">
  <a href="https://twitter.com/intent/tweet?text=<%= u @meta_title %>&url=<%= @meta_url %>"><img src="http://s9.postimg.org/9lptzzutn/twitter.png" alt="Twitter link" /></a><a href="https://www.facebook.com/sharer/sharer.php?u=<%= @meta_url %>"><img src="http://s9.postimg.org/wboysze17/facebook.png" alt="Facebook link" /></a>
</section>

<% if @podcast && @podcast_show_header != false %>
  <section id="podcast-header">
    <%= render :partial => "podcasts/header", :locals => {:podcast => @podcast, show_form: true, wrapper_class: @podcast_header_wrapper} %>
  </section>
<% end %>

<div id="content">
  <%= yield %>
</div>

<% if @podcast && @podcast_show_footer != false %>
  <div class="podcast-footer">
    <div class="inner">
      <%= render :partial => "podcasts/subscribe_new", :locals => {:podcast => @podcast} %>
    </div>
  </div>
<% end %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42341164-1', 'auto');
  ga('send', 'pageview');
</script>
</body>
</html>